apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry
spec:
  storageClassName: docker-registry
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  labels:
    app: docker-registry
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: docker-registry
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docker-registry
  name: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  strategy: {}
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
      - image: registry
        name: registry
        resources: {}
        volumeMounts:
          - name: registry-storage
            mountPath: /var/lib/registry
          - name: registry-config
            mountPath: /etc/docker-registry

      volumes:
        - name: registry-storage
          persistentVolumeClaim:
            claimName: docker-registry
        - name: registry-config
          configMap:
            defaultMode: 420
            name: docker-registry-config
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-docker-registry
spec:
  tls:
    - hosts:
      - registry.dev.fullbacksystems.com
      # This assumes tls-secret exists and the SSL
      # certificate contains a CN for foo.bar.com
      secretName: dev-cert
  rules:
  - host: registry.dev.fullbacksystems.com
    http:
      paths:
      - path: /
        backend:
          serviceName: docker-registry
          servicePort: 5000
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: docker-registry
  name: docker-registry-config
  namespace: default
data:
  config.yml: |-
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    http:
      addr: :5000
      headers:
        X-Content-Type-Options:
        - nosniff
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
    version: 0.1
