apiVersion: v1
kind: Service
metadata:
  name: ant-hello-world
  labels:
    app: hello-world
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8000
      name: http
      protocol: TCP
  selector:
    app: hello-world
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ant-hello-world
  labels:
    app: hello-world
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: crccheck/hello-world:latest
        ports:
        - containerPort: 8000
