apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-fullback-website
spec:
  tls:
    - hosts:
      - website.dev.fullbacksystems.com
      # This assumes tls-secret exists and the SSL
      # certificate contains a CN for foo.bar.com
      secretName: dev-cert
  rules:
  - host: website.dev.fullbacksystems.com
    http:
      paths:
      - path: /
        backend:
          serviceName: fullback-website
          servicePort: 8080
