# Custom values for stable/docker-registry
service:
  name: registry
  type: ClusterIP
  # clusterIP:
  port: 5000
  # nodePort:
  annotations: {}
  # foo.io/bar: "true"
ingress:
  enabled: true
  path: /
  # Used to create an Ingress record.
  hosts:
    - registry.dev.fullbacksystems.com
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "false"
    # Customise ingress object to allow for larger body sizes to void 413
    # content to large errors when pushing images
    nginx.ingress.kubernetes.io/proxy-body-size: 64m
  labels: {}
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
    - hosts:
      - registry.dev.fullbacksystems.com
      # This assumes tls-secret exists and the SSL
      # certificate contains a CN for foo.bar.com
      secretName: hello-dev
